### ISSUE TITLE
Mod versions

### ISSUE THREAD

**Issue by AlatarQ** [circlesabound/fctrl#5] opened 2024-03-31 11:24 UTC
Mod management page has problems with versions
adding fo example  "flib"  adds flib 0.9.2 while newest is 0.14.0, manually changing to 0.14.0 before save doesn't help, it still download 0.9.2

**Comment by circlesabound** [comment] 2024-04-03 23:57
Hi @AlatarQ , this bad sort behaviour for the version list was fixed in c1c6cf5 but only for the already existing entries in the mod list, not in the new entry part at the bottom.

While this is being fixed, is it possible to work around by saving and downloading the incorrect version, then refreshing the list and selecting the right version after?

**Comment by AlatarQ** [comment] 2024-04-04 23:11
I can't get mod list to do anything at all except to download new mod, changing version has no effect  (modlist does save, timestamp updates), but no change in files on server. 
some snooping around:
[2024-04-04T22:54:13Z INFO  agent::server::mods] Mods to install:
[2024-04-04T22:54:13Z INFO  agent::server::mods] Mods to delete:
web app get current version correctly and push selected version correctly too
and i would suggest to add column with "current version", and now it's really confusing at start how this list works

**Comment by circlesabound** [comment] 2024-04-09 00:33
@AlatarQ the list populates with the current version selected in the drop-down control, you can click the drop down and change the version to a different one that you want and it will be registered as a change to be made on the server side.

I just pushed a fix for several issues related to adding mods to the list:
- the sort in the version list for mod to be added should be in the right order now
- manually chosen version should transfer to the actual list instead of being ignored in UX


Could you please try with the new build and let me know if you still encounter any issues?

**Comment by AlatarQ** [comment] 2024-04-09 20:04
Mod version lists correctly showing current version. Changing version works fine too. Only  thing not working is installing specific version when adding new mod, it download latest version. It's not very needed function, just reporting for completion.

**Comment by circlesabound** [comment] 2024-04-15 02:17
@AlatarQ I'm unable to reproduce downloading the latest version of a newly added mod when the version is specified, with either of the following variations of steps:

Variant A:
1. Type the mod name into the text box
2. Select a different version for the yet-to-be-added mod
3. Press the `+` to add the entry to the list
4. Press the Save button to submit

Variant B:
1. Type the mod name into the text box
2. Press the `+` to add the entry to the list
3. Select a different version for the newly added mod in the entry list
4. Press the Save button to submit

For me, both variations submit the correct version to the server side. I tested this using the `flib` mod, both with an initially empty mod list as well as a mod list with pre-existing entries.

Could you provide give a detailed step breakdown which leads to the incorrect version being requested?

**Comment by AlatarQ** [comment] 2024-04-15 10:27
Variant A

https://github.com/circlesabound/fctrl/assets/76711624/27fc7af1-d9ad-443c-8ee3-bbf4ca20487f

**Comment by circlesabound** [comment] 2024-04-22 05:40
I've been able to reproduce the bug on Microsoft Edge, I will update on further progress

**Closed as completed** 2024-04-23 06:37 UTC
Labels: bug
